import './App.css';
import { Container } from './common/Container';
import { Header } from './header/Header';
import { Main } from './main/Main';

export const App = () => {
  return (
    <div>
      <Container>
        <Header />
      </Container>
      <Container>
        <Main isLoading={true} />
        <Main hasError={true} />
        <Main data={data} />
      </Container>
      <Container solidColor="#dedede">footer</Container>
      {/* header */}
      {/* main */}
      {/* footer */}
    </div>
  );
};

const data = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/dWvDlTkt9VEGCDww6IzNRgm8fRQ.jpg',
      id: 457332,
      title: 'Hidden Strike',
      original_language: 'en',
      original_title: 'Hidden Strike',
      overview:
        'Two elite soldiers must escort civilians through a gauntlet of gunfire and explosions.',
      poster_path: '/zsbolOkw8RhTU4DKOrpf4M7KCmi.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 53],
      popularity: 293.441,
      release_date: '2023-07-06',
      video: false,
      vote_average: 7.217,
      vote_count: 127,
    },
    {
      adult: false,
      backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
      id: 346698,
      title: 'Barbie',
      original_language: 'en',
      original_title: 'Barbie',
      overview:
        'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
      poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
      media_type: 'movie',
      genre_ids: [35, 12, 14],
      popularity: 4493.487,
      release_date: '2023-07-19',
      video: false,
      vote_average: 7.543,
      vote_count: 1688,
    },
    {
      adult: false,
      backdrop_path: '/iEFuHjqrE059SmflBva1JzDJutE.jpg',
      id: 496450,
      title: 'Miraculous: Ladybug & Cat Noir, The Movie',
      original_language: 'fr',
      original_title: 'Miraculous - le film',
      overview:
        'A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.',
      poster_path: '/bBON9XO9Ek0DjRwMBnJNCwC96Cd.jpg',
      media_type: 'movie',
      genre_ids: [16, 10751, 28, 14, 10749],
      popularity: 533.05,
      release_date: '2023-07-05',
      video: false,
      vote_average: 8.316,
      vote_count: 147,
    },
    {
      adult: false,
      backdrop_path: '/znUYFf0Sez5lUmxPr3Cby7TVJ6c.jpg',
      id: 447277,
      title: 'The Little Mermaid',
      original_language: 'en',
      original_title: 'The Little Mermaid',
      overview:
        'The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.',
      poster_path: '/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg',
      media_type: 'movie',
      genre_ids: [12, 10751, 14, 10749],
      popularity: 4075.869,
      release_date: '2023-05-18',
      video: false,
      vote_average: 6.422,
      vote_count: 1220,
    },
    {
      adult: false,
      backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
      id: 872585,
      title: 'Oppenheimer',
      original_language: 'en',
      original_title: 'Oppenheimer',
      overview:
        'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
      poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
      media_type: 'movie',
      genre_ids: [18, 36],
      popularity: 1155.971,
      release_date: '2023-07-19',
      video: false,
      vote_average: 8.344,
      vote_count: 1033,
    },
    {
      adult: false,
      backdrop_path: '/zzbEAP5d1Ci0QKitpaA8PykHIj4.jpg',
      id: 926008,
      title: 'The Beanie Bubble',
      original_language: 'en',
      original_title: 'The Beanie Bubble',
      overview:
        'Ty was a frustrated toy salesman until his collaboration with three women turned his stuffed animals into a defining ’90s trend. This behind-the-scenes look at history’s biggest toy craze is a wild story about what—and who—is valued in this world.',
      poster_path: '/jgAxa30NBLZYxbJjZxUTatIAdCa.jpg',
      media_type: 'movie',
      genre_ids: [35, 18],
      popularity: 35.568,
      release_date: '2023-07-21',
      video: false,
      vote_average: 7.26,
      vote_count: 25,
    },
    {
      adult: false,
      backdrop_path: '/kCONdNN8JJFM6GAnzc03pBFjRFH.jpg',
      id: 1083862,
      title: 'Resident Evil: Death Island',
      original_language: 'ja',
      original_title: 'バイオハザード：デスアイランド',
      overview:
        'In San Francisco, Jill Valentine is dealing with a zombie outbreak and a new T-Virus, Leon Kennedy is on the trail of a kidnapped DARPA scientist, and Claire Redfield is investigating a monstrous fish that is killing whales in the bay. Joined by Chris Redfield and Rebecca Chambers, they discover the trail of clues from their separate cases all converge on the same location, Alcatraz Island, where a new evil has taken residence and awaits their arrival.',
      poster_path: '/qayga07ICNDswm0cMJ8P3VwklFZ.jpg',
      media_type: 'movie',
      genre_ids: [16, 28, 27],
      popularity: 3126.169,
      release_date: '2023-06-22',
      video: false,
      vote_average: 7.96,
      vote_count: 252,
    },
    {
      adult: false,
      backdrop_path: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
      id: 447365,
      title: 'Guardians of the Galaxy Vol. 3',
      original_language: 'en',
      original_title: 'Guardians of the Galaxy Vol. 3',
      overview:
        'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
      poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
      media_type: 'movie',
      genre_ids: [878, 12, 28],
      popularity: 2050.089,
      release_date: '2023-05-03',
      video: false,
      vote_average: 8.108,
      vote_count: 3606,
    },
    {
      adult: false,
      backdrop_path: '/df8ya9FKghk0U45G2nJru6ZOuUK.jpg',
      id: 1140066,
      title: 'Paradise',
      original_language: 'de',
      original_title: 'Paradise',
      overview:
        'A man sees the dark side of the time-manipulating biotech company he works for when a crushing debt forces his wife to give up 40 years of her own life.',
      poster_path: '/yGz88hNPcHUJkUx7MPm0Ue6GZt7.jpg',
      media_type: 'movie',
      genre_ids: [53, 878, 28],
      popularity: 22.604,
      release_date: '2023-06-24',
      video: false,
      vote_average: 6.9,
      vote_count: 42,
    },
    {
      adult: false,
      backdrop_path: '/yF1eOkaYvwiORauRCPWznV9xVvi.jpg',
      id: 298618,
      title: 'The Flash',
      original_language: 'en',
      original_title: 'The Flash',
      overview:
        "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
      poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 4631.142,
      release_date: '2023-06-13',
      video: false,
      vote_average: 6.913,
      vote_count: 1803,
    },
    {
      adult: false,
      backdrop_path: '/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg',
      id: 667538,
      title: 'Transformers: Rise of the Beasts',
      original_language: 'en',
      original_title: 'Transformers: Rise of the Beasts',
      overview:
        'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
      poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 4090.661,
      release_date: '2023-06-06',
      video: false,
      vote_average: 7.505,
      vote_count: 2098,
    },
    {
      adult: false,
      backdrop_path: '/4vlsYpItGVZN1UWZGqQBoCzrUSw.jpg',
      id: 1030987,
      title: 'Sympathy for the Devil',
      original_language: 'en',
      original_title: 'Sympathy for the Devil',
      overview:
        'After being forced to drive a mysterious passenger at gunpoint, a man finds himself in a high-stakes game of cat and mouse where it becomes clear that not everything is as it seems.',
      poster_path: '/tpc83yJ7w5sqvLeKp5Iktj3n2fS.jpg',
      media_type: 'movie',
      genre_ids: [53],
      popularity: 38.29,
      release_date: '2023-07-20',
      video: false,
      vote_average: 7.4,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/5iXZJyEY2sDQMs7dHo9gH3qijmL.jpg',
      id: 881209,
      title: 'Happiness for Beginners',
      original_language: 'en',
      original_title: 'Happiness for Beginners',
      overview:
        'At a crossroads after her divorce, a schoolteacher ventures toward a fresh start in life — and love — when she signs up for a grueling group hiking trip.',
      poster_path: '/rK4jb2t3J98IXjY9O3nc8bX9yqt.jpg',
      media_type: 'movie',
      genre_ids: [10749, 12, 35],
      popularity: 97.335,
      release_date: '2023-07-27',
      video: false,
      vote_average: 6.534,
      vote_count: 44,
    },
    {
      adult: false,
      backdrop_path: '/fIQfdZ6fqf9mIbqBaexbgIEIk5K.jpg',
      id: 864168,
      title: 'Joy Ride',
      original_language: 'en',
      original_title: 'Joy Ride',
      overview:
        'Four Asian-American friends travel through Asia in search of one of their birth mothers. Along the way, their experience becomes one of bonding, friendship, belonging and no-holds-barred debauchery.',
      poster_path: '/lTZ3r9NBdbrR6NA90v3hFYqd6TC.jpg',
      media_type: 'movie',
      genre_ids: [35],
      popularity: 83.899,
      release_date: '2023-06-22',
      video: false,
      vote_average: 7.17,
      vote_count: 50,
    },
    {
      adult: false,
      backdrop_path: '/Als2QyqbLgT5G3rwTGJta8QQfqP.jpg',
      id: 616747,
      title: 'Haunted Mansion',
      original_language: 'en',
      original_title: 'Haunted Mansion',
      overview:
        'A woman and her son enlist a motley crew of so-called spiritual experts to help rid their home of supernatural squatters.',
      poster_path: '/jUjg01KWd11nycbtXhJKghZFD7V.jpg',
      media_type: 'movie',
      genre_ids: [35, 14, 9648],
      popularity: 249.943,
      release_date: '2023-07-26',
      video: false,
      vote_average: 7.058,
      vote_count: 43,
    },
    {
      adult: false,
      backdrop_path: '/kIMYSzp1fH1H9adKplekLD9BuNi.jpg',
      id: 1003581,
      title: 'Justice League: Warworld',
      original_language: 'en',
      original_title: 'Justice League: Warworld',
      overview:
        'Until now, the Justice League has been a loose association of superpowered individuals. But when they are swept away to Warworld, a place of unending brutal gladiatorial combat, Batman, Superman, Wonder Woman and the others must somehow unite to form an unbeatable resistance able to lead an entire planet to freedom.',
      poster_path: '/qmevjlNDaWoEughGlXFWHbQ4TaR.jpg',
      media_type: 'movie',
      genre_ids: [16, 28, 878],
      popularity: 466.686,
      release_date: '2023-07-25',
      video: false,
      vote_average: 7.896,
      vote_count: 53,
    },
    {
      adult: false,
      backdrop_path: '/628Dep6AxEtDxjZoGP78TsOxYbK.jpg',
      id: 575264,
      title: 'Mission: Impossible - Dead Reckoning Part One',
      original_language: 'en',
      original_title: 'Mission: Impossible - Dead Reckoning Part One',
      overview:
        "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
      poster_path: '/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 53],
      popularity: 558.908,
      release_date: '2023-07-08',
      video: false,
      vote_average: 7.749,
      vote_count: 766,
    },
    {
      adult: false,
      backdrop_path: '/zAruyEXJ4Egwm3y8X2JUR9ODt3p.jpg',
      id: 1147049,
      title: "Big Nunu's Little Heist",
      original_language: 'en',
      original_title: "Big Nunu's Little Heist",
      overview:
        "An ex-soldier turned deliveryman is dragged into a local kingpin's bumbling gang to pull off a daring heist in an infamous South African township.",
      poster_path: '/sb6xC84pnvVXCs1BrlheRTUmMcI.jpg',
      media_type: 'movie',
      genre_ids: [35, 28],
      popularity: 51.685,
      release_date: '2023-07-28',
      video: false,
      vote_average: 8.167,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: '/fgw4rFs4XMWdJTWp1eMacHKQqbZ.jpg',
      id: 603692,
      title: 'John Wick: Chapter 4',
      original_language: 'en',
      original_title: 'John Wick: Chapter 4',
      overview:
        'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
      poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
      media_type: 'movie',
      genre_ids: [28, 53, 80],
      popularity: 1051.36,
      release_date: '2023-03-22',
      video: false,
      vote_average: 7.8,
      vote_count: 3975,
    },
    {
      adult: false,
      backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
      id: 569094,
      title: 'Spider-Man: Across the Spider-Verse',
      original_language: 'en',
      original_title: 'Spider-Man: Across the Spider-Verse',
      overview:
        'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
      poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 16, 878],
      popularity: 1058.671,
      release_date: '2023-05-31',
      video: false,
      vote_average: 8.472,
      vote_count: 2551,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
